package entities;
// Generated Dec 9, 2017 1:22:07 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import utils.IgnoreTable;

/**
 * MountLocation generated by hbm2java
 */
@Entity
@Table(name = "mountLocation",
        catalog = "tireControl"
)
public class MountLocation implements java.io.Serializable {

    @IgnoreTable
    private Integer id;
    private String name;
    @IgnoreTable
    private Set<Mount> mounts = new HashSet<Mount>(0);

    public MountLocation() {
    }

    public MountLocation(String name) {
        this.name = name;
    }

    public MountLocation(String name, Set<Mount> mounts) {
        this.name = name;
        this.mounts = mounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mountLocation")
    public Set<Mount> getMounts() {
        return this.mounts;
    }

    public void setMounts(Set<Mount> mounts) {
        this.mounts = mounts;
    }

    @Override
    public String toString() {
        return this.name;
    }
}
