package entities;
// Generated Dec 9, 2017 1:22:07 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import utils.IgnoreTable;

/**
 * Mount generated by hbm2java
 */
@Entity
@Table(name = "mount",
        catalog = "tireControl"
)
public class Mount implements java.io.Serializable {

    @IgnoreTable
    private Integer id;
    private MountLocation mountLocation;
    @IgnoreTable
    private Retread retread;
    private Truck truck;
    private Date date;
    private double km;
    @IgnoreTable
    private Set<Unmount> unmounts = new HashSet<Unmount>(0);

    public Mount() {
        this.mountLocation = new MountLocation();
        this.retread = new Retread();
        this.truck = new Truck();
    }

    public Mount(int id, MountLocation mountLocation, Retread retread, Truck truck, Date date, double km) {
        this.id = id;
        this.mountLocation = mountLocation;
        this.retread = retread;
        this.truck = truck;
        this.date = date;
        this.km = km;
    }

    public Mount(int id, MountLocation mountLocation, Retread retread, Truck truck, Date date, double km, Set<Unmount> unmounts) {
        this.id = id;
        this.mountLocation = mountLocation;
        this.retread = retread;
        this.truck = truck;
        this.date = date;
        this.km = km;
        this.unmounts = unmounts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mountLocation_id", nullable = false)
    public MountLocation getMountLocation() {
        return this.mountLocation;
    }

    public void setMountLocation(MountLocation mountLocation) {
        this.mountLocation = mountLocation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "retread_id", nullable = false)
    public Retread getRetread() {
        return this.retread;
    }

    public void setRetread(Retread retread) {
        this.retread = retread;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "truck_id", nullable = false)
    public Truck getTruck() {
        return this.truck;
    }

    public void setTruck(Truck truck) {
        this.truck = truck;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "km", nullable = false, precision = 22, scale = 0)
    public double getKm() {
        return this.km;
    }

    public void setKm(double km) {
        this.km = km;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mount")
    public Set<Unmount> getUnmounts() {
        return this.unmounts;
    }

    public void setUnmounts(Set<Unmount> unmounts) {
        this.unmounts = unmounts;
    }

}
