package entities;
// Generated Dec 9, 2017 1:22:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mount generated by hbm2java
 */
@Entity
@Table(name="mount"
    ,catalog="tireControl"
)
public class Mount  implements java.io.Serializable {


     private int id;
     private MountLocation mountLocation;
     private Retread retread;
     private Truck truck;
     private Date mountDate;
     private double mountKm;
     private Set<Unmount> unmounts = new HashSet<Unmount>(0);

    public Mount() {
    }

	
    public Mount(int id, MountLocation mountLocation, Retread retread, Truck truck, Date mountDate, double mountKm) {
        this.id = id;
        this.mountLocation = mountLocation;
        this.retread = retread;
        this.truck = truck;
        this.mountDate = mountDate;
        this.mountKm = mountKm;
    }
    public Mount(int id, MountLocation mountLocation, Retread retread, Truck truck, Date mountDate, double mountKm, Set<Unmount> unmounts) {
       this.id = id;
       this.mountLocation = mountLocation;
       this.retread = retread;
       this.truck = truck;
       this.mountDate = mountDate;
       this.mountKm = mountKm;
       this.unmounts = unmounts;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mountLocation_id", nullable=false)
    public MountLocation getMountLocation() {
        return this.mountLocation;
    }
    
    public void setMountLocation(MountLocation mountLocation) {
        this.mountLocation = mountLocation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="retread_id", nullable=false)
    public Retread getRetread() {
        return this.retread;
    }
    
    public void setRetread(Retread retread) {
        this.retread = retread;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="truck_id", nullable=false)
    public Truck getTruck() {
        return this.truck;
    }
    
    public void setTruck(Truck truck) {
        this.truck = truck;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="mountDate", nullable=false, length=19)
    public Date getMountDate() {
        return this.mountDate;
    }
    
    public void setMountDate(Date mountDate) {
        this.mountDate = mountDate;
    }

    
    @Column(name="mountKm", nullable=false, precision=22, scale=0)
    public double getMountKm() {
        return this.mountKm;
    }
    
    public void setMountKm(double mountKm) {
        this.mountKm = mountKm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mount")
    public Set<Unmount> getUnmounts() {
        return this.unmounts;
    }
    
    public void setUnmounts(Set<Unmount> unmounts) {
        this.unmounts = unmounts;
    }




}


