package entities;
// Generated Dec 9, 2017 1:22:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Retread generated by hbm2java
 */
@Entity
@Table(name="retread"
    ,catalog="tireControl"
)
public class Retread  implements java.io.Serializable {


     private Integer id;
     private BandType bandType;
     private Tire tire;
     private int number;
     private Date date;
     private double value;
     private Set<Mount> mounts = new HashSet<Mount>(0);

    public Retread() {
    }

	
    public Retread(BandType bandType, Tire tire, int number, Date date, double value) {
        this.bandType = bandType;
        this.tire = tire;
        this.number = number;
        this.date = date;
        this.value = value;
    }
    public Retread(BandType bandType, Tire tire, int number, Date date, double value, Set<Mount> mounts) {
       this.bandType = bandType;
       this.tire = tire;
       this.number = number;
       this.date = date;
       this.value = value;
       this.mounts = mounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bandType_id", nullable=false)
    public BandType getBandType() {
        return this.bandType;
    }
    
    public void setBandType(BandType bandType) {
        this.bandType = bandType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tire_id", nullable=false)
    public Tire getTire() {
        return this.tire;
    }
    
    public void setTire(Tire tire) {
        this.tire = tire;
    }

    
    @Column(name="number", nullable=false)
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="value", nullable=false, precision=22, scale=0)
    public double getValue() {
        return this.value;
    }
    
    public void setValue(double value) {
        this.value = value;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="retread")
    public Set<Mount> getMounts() {
        return this.mounts;
    }
    
    public void setMounts(Set<Mount> mounts) {
        this.mounts = mounts;
    }




}


