package entities;
// Generated Dec 9, 2017 1:22:07 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import utils.IgnoreTable;

/**
 * Tire generated by hbm2java
 */
@Entity
@Table(name = "tire",
        catalog = "tireControl"
)
public class Tire implements java.io.Serializable {

    @IgnoreTable
    private Integer id;
    private TireBrand tireBrand = new TireBrand();
    private TireModel tireModel = new TireModel();
    private TireSituation tireSituation = new TireSituation();
    private int physicalIdentification;
    private int expectedNumberRetreads;
    @IgnoreTable
    private Set<Retread> retreads = new HashSet<Retread>(0);

    public Tire() {
    }

    public Tire(TireBrand tireBrand, TireModel tireModel, TireSituation tireSituation, int physicalIdentification, int expectedNumberRetreads) {
        this.tireBrand = tireBrand;
        this.tireModel = tireModel;
        this.tireSituation = tireSituation;
        this.physicalIdentification = physicalIdentification;
        this.expectedNumberRetreads = expectedNumberRetreads;
    }

    public Tire(TireBrand tireBrand, TireModel tireModel, TireSituation tireSituation, int physicalIdentification, int expectedNumberRetreads, Set<Retread> retreads) {
        this.tireBrand = tireBrand;
        this.tireModel = tireModel;
        this.tireSituation = tireSituation;
        this.physicalIdentification = physicalIdentification;
        this.expectedNumberRetreads = expectedNumberRetreads;
        this.retreads = retreads;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tireBrand_id", nullable = false)
    public TireBrand getTireBrand() {
        return this.tireBrand;
    }

    public void setTireBrand(TireBrand tireBrand) {
        this.tireBrand = tireBrand;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tireModel_id", nullable = false)
    public TireModel getTireModel() {
        return this.tireModel;
    }

    public void setTireModel(TireModel tireModel) {
        this.tireModel = tireModel;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tireSituation_id", nullable = false)
    public TireSituation getTireSituation() {
        return this.tireSituation;
    }

    public void setTireSituation(TireSituation tireSituation) {
        this.tireSituation = tireSituation;
    }

    @Column(name = "physicalIdentification", nullable = false)
    public int getPhysicalIdentification() {
        return this.physicalIdentification;
    }

    public void setPhysicalIdentification(int physicalIdentification) {
        this.physicalIdentification = physicalIdentification;
    }

    @Column(name = "expectedNumberRetreads", nullable = false)
    public int getExpectedNumberRetreads() {
        return this.expectedNumberRetreads;
    }

    public void setExpectedNumberRetreads(int expectedNumberRetreads) {
        this.expectedNumberRetreads = expectedNumberRetreads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tire")
    public Set<Retread> getRetreads() {
        return this.retreads;
    }

    public void setRetreads(Set<Retread> retreads) {
        this.retreads = retreads;
    }

    @Override
    public String toString() {
        return "" + this.physicalIdentification;
    }

}
