package entities;
// Generated Dec 9, 2017 1:22:07 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import utils.IgnoreTable;

/**
 * Unmount generated by hbm2java
 */
@Entity
@Table(name = "unmount",
        catalog = "tireControl"
)
public class Unmount implements java.io.Serializable {

    @IgnoreTable
    private Mount mount;
    private UnmountReason unmountReason;
    private Date date;
    private double km;
    private String note;

    public Unmount() {
    }

    public Unmount(Mount mount, UnmountReason unmountReason, Date date, double km) {
        this.mount = mount;
        this.unmountReason = unmountReason;
        this.date = date;
        this.km = km;
    }

    public Unmount(Mount mount, UnmountReason unmountReason, Date date, double km, String note) {
        this.mount = mount;
        this.unmountReason = unmountReason;
        this.date = date;
        this.km = km;
        this.note = note;
    }

    @Id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mount_id", nullable = false)
    public Mount getMount() {
        return this.mount;
    }

    public void setMount(Mount mount) {
        this.mount = mount;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unmountReason_id", nullable = false)
    public UnmountReason getUnmountReason() {
        return this.unmountReason;
    }

    public void setUnmountReason(UnmountReason unmountReason) {
        this.unmountReason = unmountReason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "km", nullable = false, precision = 22, scale = 0)
    public double getKm() {
        return this.km;
    }

    public void setKm(double km) {
        this.km = km;
    }

    @Column(name = "note", length = 1000)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public String toString() {
        return "Unmount{id=" +mount.getId() +", mount=" + mount + ", unmountReason=" + unmountReason + ", date=" + date + ", km=" + km + ", note=" + note + '}';
    }
    
}
