package entities;
// Generated Dec 9, 2017 1:22:07 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Unmount generated by hbm2java
 */
@Entity
@Table(name = "unmount",
         catalog = "tireControl"
)
public class Unmount implements java.io.Serializable {

    private int id;
    private Mount mount;
    private UnmountReason unmountReason;
    private Date unmountDate;
    private double unmountKm;
    private String unmountNote;

    public Unmount() {
    }

    public Unmount(int id, Mount mount, UnmountReason unmountReason, Date unmountDate, double unmountKm) {
        this.id = id;
        this.mount = mount;
        this.unmountReason = unmountReason;
        this.unmountDate = unmountDate;
        this.unmountKm = unmountKm;
    }

    public Unmount(int id, Mount mount, UnmountReason unmountReason, Date unmountDate, double unmountKm, String unmountNote) {
        this.id = id;
        this.mount = mount;
        this.unmountReason = unmountReason;
        this.unmountDate = unmountDate;
        this.unmountKm = unmountKm;
        this.unmountNote = unmountNote;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mount_id", nullable = false)
    public Mount getMount() {
        return this.mount;
    }

    public void setMount(Mount mount) {
        this.mount = mount;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unmountReason_id", nullable = false)
    public UnmountReason getUnmountReason() {
        return this.unmountReason;
    }

    public void setUnmountReason(UnmountReason unmountReason) {
        this.unmountReason = unmountReason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "unmountDate", nullable = false, length = 19)
    public Date getUnmountDate() {
        return this.unmountDate;
    }

    public void setUnmountDate(Date unmountDate) {
        this.unmountDate = unmountDate;
    }

    @Column(name = "unmountKm", nullable = false, precision = 22, scale = 0)
    public double getUnmountKm() {
        return this.unmountKm;
    }

    public void setUnmountKm(double unmountKm) {
        this.unmountKm = unmountKm;
    }

    @Column(name = "unmountNote", length = 1000)
    public String getUnmountNote() {
        return this.unmountNote;
    }

    public void setUnmountNote(String unmountNote) {
        this.unmountNote = unmountNote;
    }

}
